1. acceso
realizado el login hasta mostar los datos
1.2 login con  sesiones

1.3 video 7 listado de suarios

1.4 modifica el usuario
1.5 modifica la foto del usuario

CREATE PROCEDURE SP_REGISTRAR_USUARIO(IN USUARIO VARCHAR(50), IN CONTRA VARCHAR(255),
IN IDROL INT,IN EMAIL VARCHAR(255), IN RUTA VARCHAR(255))
BEGIN
DECLARE CANTIDAD INT;

SET @CANTIDAD:=(SELECT COUNT(*) FROM usuario where usu_nombre =BINARY USUARIO);
IF @CANTIDAD = 0 THEN 
INSERT INTO usuario(usu_nombre,usu_contrasena,rol_id,usu_status,usu_email,usu_foto)
VALUE(USUARIO,CONTRA,IDROL,'ACTIVO',EMAIL,RUTA);
SELECT 1;
ELSE
SELECT 2;

END IF;

END




CREATE  PROCEDURE `SP_REGISTRAR_ROL`(IN ROL VARCHAR(100))
BEGIN 
DECLARE CANTIDAD INT;
SET @CANTIDAD:=(SELECT COUNT(*) FROM eps WHERE eps.`NitEPS`=NIT_EPS);
IF @CANTIDAD = 0 THEN
INSERT INTO arl (`NitEPS`, `NomEPS`,`CiudadEPS`,`DirEPS`,`TelEPS`,`EmailEps`,
 `estatus`)
VALUES (NIT_EPS,NOMBRE_EPS, CIUDAD_EPS,DIRECCION,TELEFONO_EPS ,CORREO_EPS  ,'ACTIVO');
SELECT 1;
ELSE
SELECT 2;
END IF;
END

CREATE  PROCEDURE `SP_REGISTRAR_ROL`(IN ROL VARCHAR(100))
BEGIN 
DECLARE CANTIDAD INT;
SET @CANTIDAD:=(SELECT COUNT(*) FROM eps WHERE eps.`NitEPS`=NIT_EPS);
IF @CANTIDAD = 0 THEN
INSERT INTO arl (`NitEPS`, `NomEPS`,`CiudadEPS`,`DirEPS`,`TelEPS`,`EmailEps`,
 `estatus`)
VALUES (NIT_EPS,NOMBRE_EPS, CIUDAD_EPS,DIRECCION,TELEFONO_EPS ,CORREO_EPS  ,'ACTIVO');
SELECT 1;
ELSE
SELECT 2;
END IF;
END


crud completo de rol de usuario

listado de analisis 



CREATE  PROCEDURE `SP_MODIFICAR_ESPECIALIDAD`(IN `ID` INT, 
    IN `ESPECIALIDAD_ACTUAL` VARCHAR(250), IN `ESPECIALIDAD_NUEVO` VARCHAR(250), IN `ESTATUS` VARCHAR(15))
BEGIN
DECLARE CANTIDAD INT;
IF ESPECIALIDAD_ACTUAL = ESPECIALIDAD_NUEVO THEN
    UPDATE especialidad SET
    especialidad_estatus=ESTATUS
    WHERE especialidad_id = ID;
SELECT 1;
ELSE 
SET @CANTIDAD:=(SELECT COUNT(*) FROM especialidad WHERE analisis_nombre=ESPECIALIDAD_NUEVO);
IF  @CANTIDAD = 0 THEN
UPDATE especialidad SET
especialidad_estatus=ESTATUS,
especialidad_nombre=ESPECIALIDAD_NUEVO
WHERE especialidad_id = ID;
SELECT 1;
ELSE 
SELECT 2;
END IF;
END IF;
END